### ISSUE TITLE
Things People Want

### ISSUE THREAD

**Issue by Spazdiesfirst360** [frc3223/stats#5]
Team members started suggesting things, and now that the code was re-written I have no idea what stuff does and I cannot find anything.

> I wanted it to be more specific. Like how the IRS had their's set up, but I don't want to copy their set up -Makkiah

> Oh hey can I recommend one of several options where they have a list of their tactics and you click one? Example: "This match they were; Vault focused: Defense focused: Scale: Etc" -Lauren

> So like: 1) having if they "can climb", if they "attempted", and if they "failed" or "succeeded" 2) cubes dropped and if they were trying the scale, switch, or if they were just dropped (and maybe if they knocked any cubes off) 3) "grabber" "claw" 4a) (for scale) if they have a shooter, elevator lift, hinge lift, or "Other:" 4b) (for switch) like 4a+"slam" -Makkiah

> Sounds good. I particularly like 4. I agree with adding them, also don't forget you have a notes box for anything not already in the template -Lauren

> I know, but it got to the point where I had lines of text that I copied so I could paste it in the notes box so I didn't have to type it out for every match -Makkiah

> Also maybe a more specific auto section Where we could put details about if it was attempting something but the distances were off. That happened a couple times with the scale -Maddy

> And the switch, And if they put multiple on the scale or switch (and if so, how many of those were dropped) -Makkiah

> Or if they put the cube in the wrong side -Maddy

With only two days until Districts, there is no way we can do all of these. So what do we go with and what do we ignore?

**Comment by ariovistus** [comment]
focus and type of mechanism could be dropdowns populating a string field. attempted climb is another boolean. cubes dropped is another counter. cubes placed in auto would be more counters (plus rearranging some aggregation logic). cube in wrong side could be a boolean.

Prioritization sounds like a job for Lauren. Can we move this discussion to confluence?

**Comment by Spazdiesfirst360** [comment]
Yes, we should move this to Confluence.
